// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyKlOgQYlduhum6w_T088i-Yf6Z8wOh4U',
    appId: '1:653232880008:web:95c4a07ac28cf2f550a23d',
    messagingSenderId: '653232880008',
    projectId: 'avaliacao-individual-adc',
    authDomain: 'avaliacao-individual-adc.firebaseapp.com',
    databaseURL: 'https://avaliacao-individual-adc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'avaliacao-individual-adc.appspot.com',
    measurementId: 'G-1L53X9DYY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBjzJo8SqulAuFMIA6Yy76ZvGmsRIAmmg',
    appId: '1:653232880008:android:97769ae83e3dd42550a23d',
    messagingSenderId: '653232880008',
    projectId: 'avaliacao-individual-adc',
    databaseURL: 'https://avaliacao-individual-adc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'avaliacao-individual-adc.appspot.com',
  );
}
